import = [
    "~/.config/alacritty/current_theme.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 14.0

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[selection]
semantic_escape_chars = ",│`|\"' ()[]{}<>\t"
